name: iOS CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-15.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: List available Xcode versions
        run: ls /Applications | grep Xcode

      - name: Build app
        run: |
          xcodebuild clean build \
          -project WeatherApp.xcodeproj \
          -scheme WeatherApp \
          -sdk iphonesimulator \
          -configuration Release \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
