name: iOS CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Select Xcode 16.3
        run: sudo xcode-select -s /Applications/Xcode_16.3.app

      - name: Resolve Swift Packages
        run: |
          xcodebuild -resolvePackageDependencies \
          -project WeatherApp.xcodeproj

      - name: Build app (with macro support)
        run: |
          xcodebuild clean build \
          -project WeatherApp.xcodeproj \
          -scheme WeatherApp \
          -sdk iphonesimulator \
          -configuration Release \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
