name: iOS CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List resolved Swift packages
        run: cat WeatherApp.xcworkspace/xcshareddata/swiftpm/Package.resolved || echo "No resolved file found"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Resolve Swift Packages
        run: |
          xcodebuild -resolvePackageDependencies \
          -project WeatherApp.xcodeproj

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.3.app

      - name: Build app
        run: |
          xcodebuild clean build \
          -project WeatherApp.xcodeproj \
          -scheme WeatherApp \
          -sdk iphonesimulator \
          -configuration Release \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
